<?php
$listaPaises=array(
    'afganistan',
    'alemania',
    'angola',
    'argelia',
    'argentina',
    'australia',
    'austria',
    'bangladesh',
    'belgica',
    'belice',
    'benin',
    'birmania',
    'bolivia',
    'bostwana',
    'brasil',
    'brunei',
    'bulgaria',
    'burkina faso',
    'camboya',
    'camerun',
    'canada',
    'chad',
    'chile',
    'china',
    'colombia',
    'costa de marfil',
    'costa rica',
    'croacia',
    'cuba',
    'dinamarca',
    'ecuador',
    'egipto',
    'el salvador',
    'eslovaquia',
    'eslovenia',
    'estados unidos',
    'etiopia',
    'filipinas',
    'finlandia',
    'francia',
    'gabon',
    'gambia',
    'ghana',
    'grecia',
    'guatemala',
    'guinea ecuatorial',
    'guinea',
    'guyana',
    'haiti',
    'honduras',
    'hungria',
    'india',
    'indonesia',
    'irak',
    'iran',
    'iraq',
    'irlanda',
    'israel',
    'italia',
    'japon',
    'jordania',
    'kenya',
    'liberia',
    'libia',
    'madagascar',
    'malasia',
    'malawi',
    'mali',
    'marruecos',
    'mauritania',
    'mexico',
    'mongolia',
    'mozambique',
    'namibia',
    'nicaragua',
    'niger',
    'nigeria',
    'noruega',
    'nueva zelanda',
    'paises bajos',
    'panama',
    'papua nueva guinea',
    'paquistan',
    'paraguay',
    'peru',
    'polonia',
    'portugal',
    'reino unido',
    'republica centroafricana',
    'republica checa',
    'republica del congo',
    'republica democratica del congo',
    'republica dominicana',
    'rumania',
    'rusia',
    'senegal',
    'sierra leona',
    'siria',
    'somalia',
    'sri lanka',
    'sudafrica',
    'sudan del sur',
    'sudan',
    'suecia',
    'suiza',
    'surinam',
    'tailandia',
    'taiwan',
    'tanzania',
    'togo',
    'tunez',
    'turquia',
    'ucrania',
    'uruguay',
    'venezuela',
    'vietnam',
    'zambia',
    'zimbawe'
);

?>