<?php
const ERROR_FALTAN_PARAMETROS=1;
const ERROR_NO_NUMEROS=2;
const ERROR_MAS_DE_CIEN=4;
const ERROR_MENOS_DE_CIEN=8;
const ERROR_RANGO_MESSI=16;
const ERROR_RANGO_RONALDO=32;
const ERROR_RANGO_GRIEZMANN=64;
const SIMBOLO="&hearts;";
?>